services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3101:3000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://fundflow_user:password@postgres:5432/fundflow_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
    networks:
      - backend-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fundflow_db
      POSTGRES_USER: fundflow_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
