services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:3000"  # Match the container port with the exposed port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000  # Explicitly set the port
    depends_on:
      - postgres
      - redis
    networks:
      - spndr-network
    # Add healthcheck to verify service is running
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "backend"
        env: "development"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: spndr_db
      POSTGRES_USER: spndr_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spndr-network

  postgres-shadow:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: spndr_db
      POSTGRES_USER: spndr_user
      POSTGRES_PASSWORD: password
    ports:
      - "5431:5432"
    volumes:
      - postgres-data-shadow:/var/lib/postgresql/data1
    networks:
      - spndr-network


  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - spndr-network

volumes:
  postgres-data:
  postgres-data-shadow:

networks:
  spndr-network:
    driver: bridge