services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3101:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: fundflow_db
      POSTGRES_USER: fundflow_user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:alpine
    restart: always
    networks:
      - backend-network

volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge